import React, { createContext, useState, useContext } from 'react';

const translations = {
    es: {
        myReservations: "Mis reservas",
        myFavorites: "Mis favoritos",
        newTrip: "Nuevo viaje",
        viewProfile: "Ver perfil",
        logout: "Cerrar sesión",
        searchPlaceholder: "Buscar viaje...",
        title: "Lista de viajes",
        subtitle: "Explorando aventuras",
        createTrip: "Crear Viaje",
        destination: "Destino",
        startDate: "Fecha inicio",
        endDate: "Fecha fin",
        tripTitle: "Título del viaje",
        back: "Volver",
        save: "Guardar",
        edit: "Editar",
        phone: "Teléfono",
        birthday: "Fecha de nacimiento",
        registrationDate: "Fecha de registro",
        name: "Nombre completo",
        tripsReserved: "Viajes reservados",
        tripsCompleted: "Viajes completados",
        confirmReserva: "Confirmar Reserva",
        memberSince: "Miembro desde",
        noTrips: "Aún no tienes viajes",
        noTripsDesc: "Crea tu primer viaje y empieza a planificar tu próxima aventura.",
        all: "Todos",
        creador: "Creador",
        admin: "Admin",
        colaborador: "Colaborador",
        reservedTrips: "Viajes reservados",
        completedTrips: "Viajes completados",
        loadingTrips: "Sincronizando tus aventuras...",
        exploring: "Explorando",
        destinations: "destinos",
        noResults: "Sin resultados",
        tryAnother: "Prueba con otro filtro o crea un nuevo viaje.",
        reservaTitle: "Pago de Reserva",
        reservaDesc: "Introduce tus datos de pago para confirmar el viaje.",
        passengers: "Pasajeros",
        class: "Clase",
        economy: "Económica",
        business: "Business",
        summary: "Resumen",
        duration: "Duración",
        days: "Días",
        vuelo: "Vuelo",
        seguro: "Seguro",
        total: "Total a Pagar",
        payWith: "Método de Pago",
        payNow: "Pagar y Confirmar",
        errorFields: "Por favor, rellena todos los campos",
        emptyFavorites: "No tienes favoritos",
        emptyReservations: "No tienes reservas aún",
        viewDetails: "Ver detalles",
        reserve: "Reservar",
        cardNumber: "Número de tarjeta",
        expiry: "Caducidad",
        cvv: "CVV",
        paymentSuccess: "¡Pago realizado con éxito! Tu viaje está confirmado.",
        paymentSuccessShort: "Pago realizado con éxito",
        bookedTrips: "Viajes ya reservados",
        price: "Precio",
        loginWithGoogle: "Entrar con Google",
        loginTitle: "Inicia sesión",
        loginSubtitle: "Bienvenido de nuevo",
        loginBtn: "Entrar",
        noAccount: "¿No tienes cuenta?",
        registerNow: "Regístrate ahora",
        registerTitle: "Crea tu cuenta",
        registerSubtitle: "Únete a la comunidad",
        registerBtn: "Registrarse",
        haveAccount: "¿Ya tienes cuenta?",
        loginNow: "Inicia sesión",
        email: "Correo electrónico",
        password: "Contraseña",
        savedDestinations: "Tus destinos guardados",
        tripSummary: "Este viaje incluye alojamiento premium, guías locales y actividades exclusivas.",
        paymentInfo: "Procede con el pago seguro desde tu dispositivo móvil",
        aboutPlace: "Descripción del lugar"
    },
    en: {
        myReservations: "My reservations",
        myFavorites: "My favorites",
        newTrip: "New trip",
        viewProfile: "View profile",
        logout: "Logout",
        searchPlaceholder: "Search trip...",
        title: "Trip List",
        subtitle: "Exploring adventures",
        createTrip: "Create Trip",
        destination: "Destination",
        startDate: "Start Date",
        endDate: "End Date",
        tripTitle: "Trip Title",
        back: "Back",
        save: "Save",
        edit: "Edit",
        phone: "Phone",
        birthday: "Birthday",
        registrationDate: "Registration date",
        name: "Full name",
        tripsReserved: "Reserved Trips",
        tripsCompleted: "Completed Trips",
        confirmReserva: "Confirm Reservation",
        memberSince: "Member since",
        noTrips: "No trips yet",
        noTripsDesc: "Create your first trip and start planning your next adventure.",
        all: "All",
        creador: "Creator",
        admin: "Admin",
        colaborador: "Contributor",
        reservedTrips: "Reserved trips",
        completedTrips: "Completed trips",
        loadingTrips: "Syncing your adventures...",
        exploring: "Exploring",
        destinations: "destinations",
        noResults: "No results",
        tryAnother: "Try another filter or create a new trip.",
        reservaTitle: "Reservation Payment",
        reservaDesc: "Enter your payment details to confirm the trip.",
        passengers: "Passengers",
        class: "Class",
        economy: "Economy",
        business: "Business",
        summary: "Summary",
        duration: "Duration",
        days: "Days",
        vuelo: "Flight",
        seguro: "Insurance",
        total: "Total to Pay",
        payWith: "Payment Method",
        payNow: "Pay and Confirm",
        errorFields: "Please fill all fields",
        emptyFavorites: "No favorites yet",
        emptyReservations: "No reservations yet",
        viewDetails: "View details",
        reserve: "Reserve",
        cardNumber: "Card Number",
        expiry: "Expiry",
        cvv: "CVV",
        paymentSuccess: "Payment successful! Your trip is confirmed.",
        paymentSuccessShort: "Payment successful",
        bookedTrips: "Booked Trips",
        price: "Price",
        loginWithGoogle: "Login with Google",
        loginTitle: "Login",
        loginSubtitle: "Welcome back",
        loginBtn: "Login",
        noAccount: "Don't have an account?",
        registerNow: "Register now",
        registerTitle: "Create Account",
        registerSubtitle: "Join the community",
        registerBtn: "Sign Up",
        haveAccount: "Already have an account?",
        loginNow: "Login here",
        email: "Email address",
        password: "Password",
        savedDestinations: "Your saved destinations",
        tripSummary: "This trip includes premium accommodation, local guides and exclusive activities.",
        paymentInfo: "Proceed with secure payment from your mobile device",
        aboutPlace: "About the place"
    }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [lang, setLang] = useState(localStorage.getItem('lang') || 'es');

    const t = (key) => translations[lang][key] || key;

    const toggleLanguage = () => {
        const newLang = lang === 'es' ? 'en' : 'es';
        setLang(newLang);
        localStorage.setItem('lang', newLang);
    };

    return (
        <LanguageContext.Provider value={{ lang, t, toggleLanguage }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
